// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTz4e2dUh9V3ewGx8x62rcEnThhz2amzM',
    appId: '1:953483459664:web:9c31aa68bc7220ba242555',
    messagingSenderId: '953483459664',
    projectId: 'ar-foodview',
    authDomain: 'ar-foodview.firebaseapp.com',
    storageBucket: 'ar-foodview.firebasestorage.app',
    measurementId: 'G-9BXH7BVYDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuLOZrojO7nG3EA3iKbAvbEiwKM6lDvps',
    appId: '1:953483459664:android:f7d27ca2d2375e76242555',
    messagingSenderId: '953483459664',
    projectId: 'ar-foodview',
    storageBucket: 'ar-foodview.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd6LpKYbHAKSoe3XAgsYXTWfIBvong-xo',
    appId: '1:953483459664:ios:eb09f33b9bb82b73242555',
    messagingSenderId: '953483459664',
    projectId: 'ar-foodview',
    storageBucket: 'ar-foodview.firebasestorage.app',
    iosBundleId: 'com.ar.foodview',
  );
}
